trigger:
  branches:
    include:
      - development
      - staging
      - master

variables:
  azureSubscriptionEndpoint: Pay-As-You-Go(72d71eb8-41df-488b-989a-d1de611a5935)
  WebAppName: VT-OmniChannelCommunication

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12.18.3
    displayName: Install Node.js

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npx ng build --configuration=$(Build.SourceBranchName)
    displayName: Build $(Build.SourceBranchName)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/omnichannelcommunication'
      ArtifactName: web-app-$(Build.SourceBranchName)
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'
